name: Docker Build

# 触发时机：PR到staging/main分支、push到staging/main分支时
on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # 拉取代码
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # 初始化Docker构建环境
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # 构建上下文为项目根目录
        push: false  # 仅构建镜像，暂不推送（如需推送可改为true并配置仓库凭证）
        tags: my-dedupe-app:latest  # 镜像标签（可自定义）
          
